apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yml
- service.yml

images:
- name: goserver
  newName: ivanmoura/gitopsfc
  newTag: 42809db996ed1519bb76dfc3bf3c255d7bba5c93
